import { CircleGauge, Goal, Landmark, Target } from 'lucide-react'
import { AppShell, PageHeading } from '../_components/app-shell'
import { createClient } from '@/lib/supabase/server'
import { requireCompanyPermission } from '@/lib/workspace/server'
import { saveCommercialGoalAction } from './actions'
import styles from './page.module.css'

type Row=Record<string,unknown>
type RpcClient={rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}>}
const integer=new Intl.NumberFormat('pt-BR'),decimal=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}),money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}),compactMoney=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',notation:'compact',maximumFractionDigits:1})
const months=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
const text=(v:unknown,f='')=>v===null||v===undefined?f:String(v),amount=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0}
const asRecord=(v:unknown):Row=>v&&typeof v==='object'&&!Array.isArray(v)?v as Row:{},asRows=(v:unknown):Row[]=>Array.isArray(v)?v.filter((x)=>x&&typeof x==='object'&&!Array.isArray(x)) as Row[]:[]
const iso=(d:Date)=>d.toISOString().slice(0,10)

export default async function GoalsPage(){
  const workspace=await requireCompanyPermission('overview_view'),supabase=await createClient(),rpc=supabase as unknown as RpcClient
  const now=new Date(),today=iso(now),year=now.getUTCFullYear()
  const {data,error}=await rpc.rpc('get_goals_command_center',{target_company_id:workspace.company.id,as_of_date:today})
  if(error)return <AppShell companyName={workspace.company.name} role={workspace.membership.role} permissions={workspace.permissions}><section className="workspace-error"><strong>Não foi possível carregar as metas.</strong><span>{error.message}</span></section></AppShell>
  const payload=asRecord(data),summary=asRecord(payload.summary),progress=asRecord(payload.vgv_progress),catalog=asRows(payload.catalog),indicatorSummary=asRows(payload.indicator_summary),goals=asRows(payload.goals),developments=asRows(payload.developments),portfolios=asRows(payload.portfolios)
  const canManage=['admin','manager'].includes(workspace.membership.role)
  const catalogWithSummary=catalog.map((item)=>({...item,summary:indicatorSummary.find((row)=>text(row.indicator_key)===text(item.key))}))
  const companyYearGoals=goals.filter((g)=>text(g.scope_type)==='company'&&new Date(`${text(g.period_start)}T12:00:00Z`).getUTCFullYear()===year)
  const monthMap=new Map<string,Row>();for(const g of companyYearGoals){const m=new Date(`${text(g.period_start)}T12:00:00Z`).getUTCMonth();monthMap.set(`${text(g.indicator_key)}:${m}`,g)}
  const monthStart=new Date(Date.UTC(year,now.getUTCMonth(),1)),monthEnd=new Date(Date.UTC(year,now.getUTCMonth()+1,0))
  const target=amount(progress.target),realized=amount(progress.realized),attainment=amount(progress.attainment_pct),gap=amount(progress.gap)
  return <AppShell companyName={workspace.company.name} role={workspace.membership.role} permissions={workspace.permissions}>
    <PageHeading eyebrow="Metas" title="Planejamento comercial" context="Indicadores operacionais, VGV e escopos comerciais sem planilhas paralelas"/>
    <section className={styles.metrics}><article><span>Indicadores</span><strong>{integer.format(amount(summary.indicators)+1)}</strong><small>7 operacionais + VGV</small><Target size={17}/></article><article><span>Metas definidas</span><strong>{integer.format(amount(summary.defined))}</strong><small>{integer.format(amount(summary.drafts))} períodos ainda zerados</small><Goal size={17}/></article><article><span>VGV vigente</span><strong>{target>0?compactMoney.format(target):'—'}</strong><small>{target>0?`${decimal.format(attainment)}% realizado`:'não definido'}</small><Landmark size={17}/></article><article><span>Gap VGV</span><strong>{target>0?compactMoney.format(Math.max(gap,0)):'—'}</strong><small>{target>0?`${compactMoney.format(realized)} realizado`:'aguardando meta'}</small><CircleGauge size={17}/></article></section>
    <section className={styles.catalog}><header><div><span>COBERTURA</span><h2>O que já tem meta definida</h2></div><small>zero significa “não definida” no piloto atual</small></header><div>{catalogWithSummary.map((item)=>{const s=asRecord(item.summary);const periods=amount(s.periods),defined=amount(s.defined);return <article key={text(item.key)}><div><b>{text(item.label)}</b><span>{text(item.key)}</span></div><strong>{integer.format(defined)}/{integer.format(periods||0)}</strong><i><em style={{width:`${periods?defined/periods*100:0}%`}}/></i></article>})}</div></section>
    {canManage?<section className={styles.panel}><header><div><span>DEFINIR / ATUALIZAR</span><h2>Meta comercial</h2></div><Target size={17}/></header><form action={saveCommercialGoalAction} className={styles.form}><label><span>Indicador</span><select name="indicator_key" defaultValue="vgv">{catalog.map((item)=><option key={text(item.key)} value={text(item.key)}>{text(item.label)}</option>)}</select></label><label><span>Escopo</span><select name="scope" defaultValue="company"><option value="company">Empresa inteira</option><optgroup label="Empreendimentos">{developments.map((d)=><option key={text(d.id)} value={`development:${text(d.id)}`}>{text(d.name)}</option>)}</optgroup><optgroup label="Carteiras">{portfolios.map((p)=><option key={text(p.id)} value={`portfolio:${text(p.id)}`}>{text(p.name)}</option>)}</optgroup></select></label><label><span>Início</span><input name="period_start" type="date" defaultValue={iso(monthStart)} required/></label><label><span>Fim</span><input name="period_end" type="date" defaultValue={iso(monthEnd)} required/></label><label><span>Valor da meta</span><input name="target_value" type="number" min="0" step="0.01" placeholder="0" required/></label><button type="submit">Salvar meta</button></form><p className={styles.help}>Use R$ para VGV e quantidade para os demais indicadores. Salvar no mesmo indicador, escopo e início atualiza o registro existente.</p></section>:null}
    <section className={styles.panel}><header><div><span>MATRIZ {year}</span><h2>Metas corporativas mensais</h2></div><small>rolagem horizontal disponível</small></header><div className={styles.matrixWrap}><table><thead><tr><th>Indicador</th>{months.map(m=><th key={m}>{m}</th>)}</tr></thead><tbody>{catalog.map((item)=><tr key={text(item.key)}><td><b>{text(item.label)}</b></td>{months.map((m,index)=>{const g=monthMap.get(`${text(item.key)}:${index}`),v=amount(g?.target_value);return <td key={m} className={v>0?styles.defined:''} title={v>0?(text(item.key)==='vgv'?money.format(v):integer.format(v)):'Não definida'}>{v>0?(text(item.key)==='vgv'?compactMoney.format(v):integer.format(v)):'—'}</td>})}</tr>)}</tbody></table></div></section>
    <section className={styles.panel}><header><div><span>HISTÓRICO</span><h2>Todos os escopos cadastrados</h2></div><small>{goals.length} registros</small></header><div className={styles.history}>{goals.slice(0,120).map(g=><article key={text(g.id)}><div><b>{text(g.indicator_name)}</b><span>{text(g.scope_name)} · {text(g.scope_type)}</span></div><span>{text(g.period_start)} → {text(g.period_end)}</span><strong>{amount(g.target_value)>0?(text(g.indicator_key)==='vgv'?money.format(amount(g.target_value)):integer.format(amount(g.target_value))):'Não definida'}</strong></article>)}</div></section>
  </AppShell>
}
