'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, BarChart3, BellRing, Building2, ChevronDown, Menu, Network, Sparkles, Users } from 'lucide-react'
import { motion, useReducedMotion } from 'framer-motion'

export const commercialWhatsappUrl = `https://wa.me/5511944511771?text=${encodeURIComponent('Olá! Conheci a VETRO pelo site e quero entender como a plataforma pode ser implementada na operação comercial da minha incorporadora.')}`
const modules = [['Parceiros','Relacionamento, performance e força comercial.',Users],['Pipeline','Oportunidades, propostas e negociações.',Network],['Empreendimentos','Performance, VGV e comportamento comercial.',Building2],['Intelligence','Dados transformados em leitura e recomendação.',Sparkles],['Equipe','Gestores, carteiras, atividades e performance.',BarChart3]] as const
const pillars = [['V1','Relacionamento','Qualidade e frequência da relação.'],['V2','Ativação','Mobilização do parceiro.'],['V3','Oportunidades','Geração real de negócios.'],['V4','Conversão','Eficiência em transformar oportunidade em venda.'],['V5','Valor','Impacto econômico e VGV.'],['V6','Consistência','Capacidade de sustentar performance.']] as const
const signals = [['Parceiro estratégico perdendo atividade','Uma imobiliária relevante reduziu as interações nos últimos 14 dias.','14:42'],['Alta ativação, baixa conversão','Há propostas ativas, mas a taxa de fechamento exige atenção.','11:08'],['Parceiro emergente','A recorrência de oportunidades cresceu 32% neste ciclo.','09:26'],['Dependência comercial','O resultado está concentrado em uma parcela pequena da rede.','Ontem'],['Oportunidades sem movimentação','Existem negociações que precisam de uma nova ação comercial.','Ontem']] as const
const reveal = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0 } }

function Brand({ priority = false }: { priority?: boolean }) { return <Image className="vetro-logo" src="/brand/vetro-logo-light.png" alt="VETRO" width={254} height={76} priority={priority} /> }
function Cta({ children, className = '' }: { children: React.ReactNode, className?: string }) { return <a className={`vetro-cta ${className}`} href={commercialWhatsappUrl} target="_blank" rel="noreferrer"><span>{children}</span><ArrowRight size={17}/></a> }
function Section({ children, className = '', id }: { children: React.ReactNode, className?: string, id?: string }) { return <section id={id} className={`vetro-section ${className}`}>{children}</section> }

function Dashboard({ hero = false }: { hero?: boolean }) {
  return <div className={`product-dashboard ${hero ? 'product-dashboard-hero' : ''}`}><aside><Image src="/brand/vetro-mark-purple.png" alt="" width={24} height={24}/><span className="active"/><span/><span/><span/><span/></aside><div className="dashboard-body"><div className="dashboard-title"><div><small>VISÃO GERAL</small><strong>Operação comercial</strong></div><span>Este mês <ChevronDown size={12}/></span></div><div className="metric-row">{[['Vendas (Mês)','R$ 48,6M','+12,4%'],['Empreendimentos','42','+8 novos'],['Parceiros ativos','128','+12 este mês'],['VETRO Score','87','Excelente']].map(([label,value,change]) => <div className="product-metric" key={label}><small>{label}</small><b>{value}</b><em>{change}</em></div>)}</div><div className="dashboard-chart"><div><small>Evolução de vendas</small><span>Últimos 7 meses</span></div><svg viewBox="0 0 520 164" preserveAspectRatio="none" aria-label="Evolução positiva de vendas"><path className="chart-grid" d="M0 35H520M0 82H520M0 129H520"/><motion.path initial={{pathLength:0}} whileInView={{pathLength:1}} viewport={{once:true}} transition={{duration:.9}} d="M8 139 L60 116 L106 124 L150 82 L194 104 L244 70 L292 99 L339 48 L389 62 L441 30 L512 15" fill="none" stroke="url(#lineGradient)" strokeWidth="4"/><defs><linearGradient id="lineGradient"><stop stopColor="#6e35ed"/><stop offset="1" stopColor="#bc9aff"/></linearGradient></defs></svg></div><div className="dashboard-bottom"><div><small>Pipeline em andamento</small><b>312 oportunidades</b><div className="pipeline-bars"><i/><i/><i/><i/></div></div><div><small>Atividades importantes</small><p>Reunião com parceiro <em>Hoje, 14:00</em></p><p>Follow-up proposta <em>Amanhã, 10:30</em></p></div></div></div></div>
}

export default function LandingClient() {
  const reduceMotion = useReducedMotion(); const transition = reduceMotion ? {duration:0} : {duration:.7, ease:[.2,.7,.2,1] as const}
  return <main className="vetro-landing">
    <header className="vetro-header"><a href="#top" aria-label="Início VETRO"><Brand priority/></a><nav aria-label="Navegação principal"><a href="#plataforma">Plataforma</a><a href="#v6">V6 Method</a><a href="#intelligence">Intelligence</a><a href="#origem">Por que VETRO</a></nav><div className="header-actions"><Link href="/login">Acessar plataforma</Link><Cta>Conhecer a VETRO</Cta><button className="menu-button" aria-label="Abrir menu"><Menu size={19}/></button></div></header>
    <Section id="top" className="hero-section"><div className="technical-grid"/><div className="hero-light"/><div className="landing-width hero-layout"><motion.div initial="hidden" animate="visible" variants={{visible:{transition:{staggerChildren:.11}}}} className="hero-copy"><motion.p variants={reveal} transition={transition} className="eyebrow"><i/>Inteligência comercial para incorporadoras</motion.p><motion.h1 variants={reveal} transition={transition}>A inteligência por trás da <em>operação comercial.</em></motion.h1><motion.div variants={reveal} transition={transition} className="hero-actions"><Cta>Conhecer a VETRO</Cta><Link href="/login" className="quiet-action">Acessar plataforma <ArrowRight size={16}/></Link></motion.div></motion.div><motion.div initial={reduceMotion ? false : {opacity:0,y:36,rotateX:4}} whileInView={{opacity:1,y:0,rotateX:0}} viewport={{once:true}} transition={{...transition,delay:.12}} className="hero-product"><div className="product-beam"/><Dashboard hero/><article className="floating-score"><small>VETRO SCORE</small><strong>87</strong><span>Excelente</span><i/></article><article className="floating-signal"><BellRing size={17}/><div><small>VETRO SIGNAL</small><b>Ativação em alta</b></div></article></motion.div><motion.div initial="hidden" whileInView="visible" viewport={{once:true}} variants={reveal} transition={transition} className="hero-description"><p>A VETRO transforma relacionamento, parceiros, pipeline, empreendimentos e vendas em visão, gestão e direção comercial.</p><div>{['Gestão de parceiros','Pipeline com visibilidade total','Inteligência aplicada','Direção comercial por dados'].map(item => <span key={item}>{item}</span>)}</div></motion.div></div></Section>
    <Section className="problem-section"><div className="landing-width"><div className="problem-intro"><p className="eyebrow">O problema</p><h2>Sua incorporadora tem dados.<br/><em>Você consegue enxergar o que eles estão dizendo?</em></h2></div><div className="fragment-map">{['Planilhas','Gestores','Imobiliárias','Corretores','Propostas','Sistemas','Empreendimentos','Controles paralelos'].map((item,index) => <motion.span key={item} initial={{opacity:0,x:index%2?38:-38}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{...transition,delay:index*.05}}>{item}</motion.span>)}<div className="unified-reading"><Image src="/brand/vetro-mark-purple.png" alt="" width={38} height={38}/><b>Leitura VETRO</b><small>visão unificada</small></div></div><div className="problem-close"><p>Quando a informação está fragmentada, a gestão também fica.</p><Cta>Quero enxergar melhor minha operação</Cta></div></div></Section>
    <Section id="plataforma" className="platform-section"><div className="landing-width"><div className="section-heading editorial"><div><p className="eyebrow">A VETRO</p><h2>Não é mais um dashboard.<br/><em>É inteligência comercial aplicada à operação.</em></h2></div><p>A plataforma conecta o que acontece no campo ao que a gestão precisa enxergar.</p></div><div className="module-ribbon">{modules.map(([name,copy,Icon],index) => <motion.article key={name} initial="hidden" whileInView="visible" viewport={{once:true}} variants={reveal} transition={{...transition,delay:index*.07}} className={index===3?'featured':''}><span>0{index+1}</span><Icon size={24}/><h3>{name}</h3><p>{copy}</p><ArrowRight size={17}/></motion.article>)}</div><div className="align-center"><Cta>Ver a VETRO na minha operação</Cta></div></div></Section>
    <Section id="v6" className="v6-section"><div className="technical-grid dim"/><div className="landing-width"><div className="v6-heading"><div><p className="eyebrow">V6 Method</p><h2>Entenda a força real de cada parceiro comercial.</h2></div><p>Vender é resultado. <em>Entender por que vende é inteligência.</em></p></div><div className="v6-orbit"><motion.div initial={{scale:.86,opacity:0}} whileInView={{scale:1,opacity:1}} viewport={{once:true}} transition={transition} className="score-core"><small>VETRO SCORE</small><strong>87</strong><b>Parceiro estratégico</b><i/></motion.div>{pillars.map(([code,title,text],index) => <motion.article initial={{opacity:0,scale:.94}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{...transition,delay:index*.08}} key={code}><span>{code}</span><h3>{title}</h3><p>{text}</p></motion.article>)}</div><div className="v6-mobile-list"><div className="score-core"><small>VETRO SCORE</small><strong>87</strong><b>Parceiro estratégico</b></div>{pillars.map(([code,title,text]) => <article key={code}><span>{code}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="align-center"><Cta>Quero analisar meus parceiros com a VETRO</Cta></div></div></Section>
    <Section id="intelligence" className="intelligence-section"><div className="landing-width intelligence-layout"><div className="intelligence-copy"><p className="eyebrow">VETRO Intelligence</p><h2>A VETRO não deve apenas mostrar o que aconteceu.</h2><h3>Ela deve mostrar <em>onde agir.</em></h3><p>Menos tempo procurando informação. Mais tempo tomando decisão.</p><Cta>Transformar dados em decisão</Cta></div><div className="signal-console">{signals.map(([title,text,time],index) => <motion.article initial="hidden" whileInView="visible" viewport={{once:true}} variants={reveal} transition={{...transition,delay:index*.07}} key={title}><div className="signal-dot"><i/></div><div><small>VETRO SIGNAL <em>{time}</em></small><h3>{title}</h3><p>{text}</p><div className="microtrend"><i/><i/><i/><i/><i/><i/></div></div></motion.article>)}</div></div></Section>
    <Section className="executive-section"><div className="landing-width"><div className="section-heading"><div><p className="eyebrow">Visão executiva</p><h2>Abra a VETRO.<br/>Entenda sua operação.</h2></div><p>VGV, vendas, parceiros, pipeline, conversão, empreendimentos, equipe, score e alertas em uma única visão.</p></div><motion.div initial={{opacity:0,y:32}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={transition} className="executive-product"><Dashboard/></motion.div><div className="align-center"><Cta>Centralizar minha operação comercial</Cta></div></div></Section>
    <Section className="mobile-section"><div className="mobile-light"/><div className="landing-width mobile-layout"><div><p className="eyebrow">Experiência mobile</p><h2>Clareza comercial em qualquer lugar.</h2><p>Acompanhe os principais sinais da sua operação e tome decisões com informação sempre à mão.</p></div><motion.div initial={reduceMotion?false:{opacity:0,rotate:9,y:28}} whileInView={{opacity:1,rotate:0,y:0}} viewport={{once:true}} transition={transition} className="phone"><div className="phone-top"><Brand/><Menu size={16}/></div><h3>Olá, time.</h3><small>Aqui está o resumo da sua operação.</small><div className="phone-metrics"><b>R$ 48,6M <small>Vendas</small></b><b>128 <small>Parceiros</small></b><b>87 <small>Score</small></b></div><div className="phone-chart"><small>Evolução de vendas</small><svg viewBox="0 0 260 80"><path d="M5 67L34 56 60 62 88 41 112 52 142 35 167 44 193 20 225 30 255 9" fill="none" stroke="#a986ff" strokeWidth="3"/></svg></div><div className="phone-activity"><small>Atividades importantes</small><p>Reunião com parceiro <em>Hoje, 14:00</em></p><p>Follow-up proposta <em>Amanhã</em></p></div></motion.div></div></Section>
    <Section id="origem" className="origin-section"><div className="origin-object"/><div className="landing-width origin-layout"><div><p className="eyebrow">Nascida da operação real</p><h2>Tecnologia construída a partir da operação real.</h2></div><div><p>A VETRO não nasceu de uma hipótese sobre como uma incorporadora deveria trabalhar.</p><p>Nasceu da rotina comercial, do relacionamento com imobiliárias, da leitura das carteiras, dos empreendimentos, das propostas, das vendas e das decisões que precisam ser tomadas todos os dias.</p><strong>A experiência comercial de campo transformada em tecnologia proprietária.</strong></div></div></Section>
    <Section className="audience-section"><div className="landing-width"><p className="eyebrow">Para quem é</p><h2>Feita para operações que precisam enxergar mais.</h2><div>{['Incorporadoras','Construtoras com operação comercial estruturada','Diretores comerciais','Heads e gerentes','Operações com rede de imobiliárias','Empresas com dados comerciais dispersos'].map((item,index) => <motion.article initial="hidden" whileInView="visible" viewport={{once:true}} variants={reveal} transition={{...transition,delay:index*.06}} key={item}><span>0{index+1}</span><p>{item}</p></motion.article>)}</div></div></Section>
    <section className="final-section"><div className="final-portal"/><div className="technical-grid"/><div className="landing-width"><Brand/><p className="eyebrow">A inteligência por trás da operação comercial</p><h2>Sua operação já produz os dados.<br/><em>Está na hora de enxergar a inteligência por trás deles.</em></h2><p>Conheça a VETRO e entenda como a plataforma pode ser aplicada à operação comercial da sua incorporadora.</p><Cta>Quero a VETRO na minha operação</Cta><small>Implantação consultiva. Fale com nosso especialista comercial.</small></div></section>
    <footer><div className="landing-width"><div><Brand/><small>A inteligência por trás da operação comercial.</small></div><nav><a href="#plataforma">Plataforma</a><a href="#v6">V6 Method</a><a href="#intelligence">Intelligence</a><a href="#origem">Por que VETRO</a><Link href="/login">Acessar plataforma</Link></nav><small>© 2026 VETRO. Todos os direitos reservados.</small></div></footer>
  </main>
}
