'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { motion, useReducedMotion } from 'framer-motion'

export const commercialWhatsappUrl = `https://wa.me/5511944511771?text=${encodeURIComponent('Olá! Conheci a VETRO pelo site e quero entender como a plataforma pode ser implementada na operação comercial da minha incorporadora.')}`

const fragments = ['Planilhas', 'Gestores', 'Imobiliárias', 'Corretores', 'Propostas', 'Sistemas', 'Empreendimentos', 'Controles paralelos']
const modules = [['Parceiros', 'Relacionamentos que movem a operação.'], ['Pipeline', 'Visibilidade para cada oportunidade.'], ['Empreendimentos', 'A leitura que conecta produto e venda.'], ['Intelligence', 'Sinais que orientam decisões.'], ['Equipe', 'Ritmo, foco e performance comercial.']]
const pillars = ['V1 Relacionamento', 'V2 Ativação', 'V3 Oportunidades', 'V4 Conversão', 'V5 Valor', 'V6 Consistência']
const signals = ['Parceiro estratégico perdendo atividade', 'Alta ativação, baixa conversão', 'Parceiro emergente', 'Dependência comercial', 'Oportunidades sem movimentação']
const audience = ['Incorporadoras', 'Construtoras com operação comercial estruturada', 'Diretores comerciais', 'Heads e gerentes', 'Operações com rede de imobiliárias', 'Empresas com dados comerciais dispersos']

function Brand({ priority = false }: { priority?: boolean }) { return <span className="vetro-logo"><Image src="/brand/vetro-logo-white.png" alt="VETRO" width={360} height={270} priority={priority} /></span> }
function Cta({ children }: { children: React.ReactNode }) { return <a className="vetro-cta" href={commercialWhatsappUrl} target="_blank" rel="noreferrer"><span>{children}</span><ArrowRight size={18} /></a> }
function ProductImage({ priority = false }: { priority?: boolean }) { return <Image className="approved-product" src="/landing/vetro-dashboard-approved.png" alt="Visão geral da plataforma VETRO" width={1448} height={1086} priority={priority} sizes="(max-width: 760px) 122vw, (max-width: 1200px) 76vw, 880px" /> }
function Section({ children, className = '', id }: { children: React.ReactNode; className?: string; id?: string }) { return <section id={id} className={`vetro-section ${className}`}>{children}</section> }

export default function LandingClient() {
  const reducedMotion = useReducedMotion()
  const reveal = reducedMotion ? {} : { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.75, ease: [.2, .7, .2, 1] as const } }
  return <main className="vetro-landing">
    <header className="vetro-header"><a href="#top" aria-label="Início VETRO"><Brand priority /></a><nav aria-label="Navegação principal"><a href="#plataforma">Solução</a><a href="#v6">Método V6</a><a href="#intelligence">Intelligence</a><a href="#origem">Sobre nós</a></nav><div className="header-actions"><Link href="/login">Entrar</Link><Link href="/login" className="header-login">Acessar plataforma <ArrowRight size={15} /></Link></div></header>
    <Section id="top" className="hero-section"><div className="technical-grid" /><div className="hero-aura" /><div className="hero-floor" /><div className="landing-width hero-layout"><motion.div {...reveal} className="hero-copy"><p className="eyebrow">Inteligência comercial para incorporadoras</p><h1>A inteligência por trás da <em>operação comercial.</em></h1><p className="hero-text">A VETRO transforma relacionamento, parceiros, pipeline, empreendimentos e vendas em visão, gestão e direção comercial.</p><div className="hero-actions"><Cta>Conhecer a VETRO</Cta><Link href="/login" className="quiet-action">Acessar plataforma <ArrowRight size={17} /></Link></div></motion.div><motion.div initial={reducedMotion ? false : { opacity: 0, y: 55, rotateX: 4 }} whileInView={{ opacity: 1, y: 0, rotateX: 0 }} viewport={{ once: true }} transition={{ duration: 0.9, delay: 0.12 }} className="hero-product"><div className="product-glow" /><ProductImage priority /></motion.div></div></Section>
    <Section className="problem-section"><div className="technical-grid dim" /><div className="landing-width"><motion.div {...reveal} className="problem-heading"><p className="eyebrow">O problema</p><h2>Sua incorporadora tem dados.<br /><em>Você consegue enxergar o que eles estão dizendo?</em></h2></motion.div><div className="fragment-field">{fragments.map((fragment, index) => <motion.span key={fragment} initial={reducedMotion ? false : { opacity: 0, y: index % 2 ? 18 : -18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08, duration: .55 }} className={`fragment fragment-${index + 1}`}>{fragment}<i /></motion.span>)}<div className="fragment-lines" /><div className="fragment-core"><Image src="/brand/vetro-mark-purple.png" alt="" width={44} height={44} /><span>leitura VETRO</span></div></div><motion.p {...reveal} className="problem-close">Quando a informação está fragmentada, a gestão também fica.</motion.p></div></Section>
    <Section id="plataforma" className="platform-section"><div className="landing-width"><motion.div {...reveal} className="platform-heading"><p className="eyebrow">A plataforma</p><h2>Não é mais um dashboard.<br /><em>É inteligência comercial aplicada à operação.</em></h2></motion.div><div className="editorial-modules">{modules.map(([name, description], index) => <article key={name}><span>0{index + 1}</span><div><h3>{name}</h3><p>{description}</p></div><ArrowRight size={23} /></article>)}</div></div></Section>
    <Section id="v6" className="v6-section"><div className="technical-grid dim" /><div className="landing-width"><motion.div {...reveal} className="v6-heading"><p className="eyebrow">V6 Method</p><h2>Entenda a força real de cada parceiro comercial.</h2><p>Vender é resultado. <em>Entender por que vende é inteligência.</em></p></motion.div><div className="v6-orbit" aria-label="Os seis pilares do método V6"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><motion.div {...reveal} className="score-core"><small>VETRO SCORE</small><strong>87</strong><span>Excelente</span></motion.div>{pillars.map((pillar, index) => <motion.span {...reveal} transition={{ duration: .55, delay: index * .07 }} className={`pillar pillar-${index + 1}`} key={pillar}>{pillar}</motion.span>)}</div><div className="v6-timeline"><div className="timeline-score"><small>VETRO SCORE</small><strong>87</strong></div>{pillars.map((pillar, index) => <span key={pillar}><i />0{index + 1} {pillar.replace(/^V\d\s/, '')}</span>)}</div></div></Section>
    <Section id="intelligence" className="intelligence-section"><div className="landing-width"><motion.div {...reveal} className="intelligence-heading"><p className="eyebrow">VETRO Intelligence</p><h2>A VETRO não deve apenas mostrar o que aconteceu.<br /><em>Ela deve mostrar onde agir.</em></h2></motion.div><div className="signal-stream"><div className="stream-line" />{signals.map((signal, index) => <article key={signal}><time>{String(9 + index).padStart(2, '0')}:{index % 2 ? '18' : '42'}</time><i /><p>{signal}</p><span>signal</span></article>)}</div></div></Section>
    <Section className="executive-section"><div className="executive-aura" /><div className="landing-width"><motion.div {...reveal} className="executive-heading"><p className="eyebrow">Visão executiva</p><h2>Abra a VETRO.<br />Entenda sua operação.</h2></motion.div><motion.div initial={reducedMotion ? false : { opacity: 0, scale: .93, y: 45 }} whileInView={{ opacity: 1, scale: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .85 }} className="executive-product"><ProductImage /></motion.div><div className="center-cta"><Cta>Centralizar minha operação comercial</Cta></div></div></Section>
    <Section className="mobile-section"><div className="mobile-aura" /><div className="landing-width mobile-layout"><motion.div {...reveal} className="mobile-copy"><p className="eyebrow">Experiência mobile</p><h2>Clareza comercial em qualquer lugar.</h2><p>Acompanhe parceiros, pipeline e inteligência em tempo real. Tome decisões mais rápidas, mesmo longe da mesa.</p></motion.div><motion.div initial={reducedMotion ? false : { opacity: 0, y: 44, rotate: 3 }} whileInView={{ opacity: 1, y: 0, rotate: 0 }} viewport={{ once: true }} transition={{ duration: .8 }} className="approved-mobile"><Image src="/landing/vetro-mobile-approved.png" alt="Experiência mobile da plataforma VETRO" width={1448} height={1086} sizes="(max-width: 760px) 140vw, 63vw" /></motion.div></div></Section>
    <Section id="origem" className="origin-section"><div className="origin-light" /><div className="landing-width origin-layout"><motion.div {...reveal}><p className="eyebrow">Nascida da operação real</p><h2>Tecnologia construída a partir da operação real.</h2></motion.div><motion.div {...reveal} className="origin-copy"><p>A VETRO não nasceu de uma hipótese sobre como uma incorporadora deveria trabalhar.</p><p>Nasceu da rotina comercial, do relacionamento com imobiliárias, da leitura das carteiras, dos empreendimentos, das propostas, das vendas e das decisões que precisam ser tomadas todos os dias.</p><strong>A experiência comercial de campo transformada em tecnologia proprietária.</strong></motion.div></div></Section>
    <Section className="audience-section"><div className="landing-width"><motion.div {...reveal}><p className="eyebrow">Para quem é</p><h2>Feita para quem vive a operação comercial.</h2></motion.div><div className="audience-list">{audience.map((item, index) => <a href={commercialWhatsappUrl} target="_blank" rel="noreferrer" key={item}><span>0{index + 1}</span><strong>{item}</strong><i /></a>)}</div></div></Section>
    <section className="final-section"><div className="technical-grid" /><div className="final-beam" /><div className="landing-width"><Brand /><p className="eyebrow">A inteligência por trás da operação comercial</p><h2>Sua operação já produz os dados.<br /><em>Está na hora de enxergar a inteligência por trás deles.</em></h2><Cta>Quero a VETRO na minha operação</Cta></div></section><footer><div className="landing-width"><Brand /><small>© 2026 VETRO. Todos os direitos reservados.</small><Link href="/login">Acessar plataforma</Link></div></footer>
  </main>
}
