'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { UserPlus } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import styles from './page.module.css'

export function CompanyInviteMember({companyId}:{companyId:string}){const router=useRouter(),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage('');setError('');const form=new FormData(event.currentTarget),fullName=String(form.get('full_name')??'').trim(),email=String(form.get('email')??'').trim().toLowerCase(),role=String(form.get('role')??'collaborator');try{const supabase=createClient();const {data,error:invokeError}=await supabase.functions.invoke('invite-member',{body:{company_id:companyId,full_name:fullName,email,role}});if(invokeError||data?.error)throw new Error(data?.message||String(data?.error||invokeError?.message||'Não foi possível enviar o convite.'));event.currentTarget.reset();setMessage(`Convite enviado para ${email}.`);router.refresh()}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível enviar o convite.')}finally{setLoading(false)}}return <form className={styles.inviteForm} onSubmit={submit}><div><UserPlus size={17}/><div><b>Liberar novo acesso</b><span>O admin da incorporadora pode criar gestor ou colaborador.</span></div></div><label><span>Nome</span><input name="full_name" maxLength={120} placeholder="Nome completo"/></label><label><span>E-mail</span><input name="email" type="email" required placeholder="usuario@empresa.com.br"/></label><label><span>Perfil</span><select name="role" defaultValue="collaborator"><option value="manager">Gestor</option><option value="collaborator">Colaborador</option></select></label><button disabled={loading} type="submit"><UserPlus size={14}/>{loading?'Enviando…':'Enviar convite'}</button>{message?<p className={styles.success}>{message}</p>:null}{error?<p className={styles.error}>{error}</p>:null}</form>}
