'use client'

import { useMemo, useState, useTransition } from 'react'
import { createClient } from '@/lib/supabase/client'
import styles from './page.module.css'

type PermissionRow={permission?:string;allowed?:boolean}
type RpcClient={rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}>}
const permissions=[['partners_view','Ver parceiros'],['partners_manage','Gerenciar parceiros'],['pipeline_view','Ver pipeline'],['opportunities_manage','Gerenciar oportunidades'],['activities_log','Registrar atividades'],['developments_view','Ver empreendimentos'],['imports_execute','Importar dados'],['intelligence_view','Intelligence / V6'],['team_view','Ver equipe']] as const
export function MemberAccessManager({companyId,userId,role,active,current}:{companyId:string;userId:string;role:string;active:boolean;current:PermissionRow[]}){const initial=useMemo(()=>new Set(current.filter(p=>p.allowed!==false).map(p=>String(p.permission))),[current]),[selected,setSelected]=useState(initial),[enabled,setEnabled]=useState(active),[message,setMessage]=useState(''),[pending,startTransition]=useTransition();const rpc=()=>createClient() as unknown as RpcClient;function togglePermission(key:string){setSelected(prev=>{const next=new Set(prev);next.has(key)?next.delete(key):next.add(key);return next})}function savePermissions(){startTransition(async()=>{setMessage('');const result=await rpc().rpc('set_member_permissions',{target_company_id:companyId,target_user_id:userId,permission_list:Array.from(selected)});setMessage(result.error?`Erro: ${result.error.message}`:'Permissões salvas.')})}function toggleActive(){startTransition(async()=>{setMessage('');const next=!enabled;const result=await rpc().rpc('set_company_member_active',{target_company_id:companyId,target_user_id:userId,new_active:next});if(result.error){setMessage(`Erro: ${result.error.message}`);return}setEnabled(next);setMessage(next?'Acesso reativado.':'Acesso desativado.')})}return <div className={styles.accessManager}>{role==='collaborator'?<details><summary>Permissões</summary><div className={styles.permissionGrid}>{permissions.map(([key,label])=><label key={key}><input checked={selected.has(key)} onChange={()=>togglePermission(key)} type="checkbox"/><span>{label}</span></label>)}</div><button disabled={pending||!enabled} onClick={savePermissions} type="button">Salvar permissões</button></details>:<span className={styles.fixedRole}>{role==='manager'?'Permissões do perfil Gestor':'Admin gerenciado pela plataforma'}</span>}{role!=='admin'?<button className={enabled?styles.deactivate:styles.activate} disabled={pending} onClick={toggleActive} type="button">{enabled?'Desativar acesso':'Reativar acesso'}</button>:null}{message?<small>{message}</small>:null}</div>}
