import { BrainCircuit, Database, Network, Settings2, ShieldCheck, UsersRound } from 'lucide-react'
import Link from 'next/link'
import { AppShell, PageHeading } from '../_components/app-shell'
import { createClient } from '@/lib/supabase/server'
import { requireCompanyPermission } from '@/lib/workspace/server'
import { CompanyInviteMember } from './company-invite-member'
import { MemberAccessManager } from './member-access-manager'
import styles from './page.module.css'

type Row=Record<string,unknown>
type RpcClient={rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}>}
const integer=new Intl.NumberFormat('pt-BR'),decimal=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}),dateTime=new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'})
const text=(v:unknown,f='')=>v===null||v===undefined?f:String(v),amount=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0},asRecord=(v:unknown):Row=>v&&typeof v==='object'&&!Array.isArray(v)?v as Row:{},asRows=(v:unknown):Row[]=>Array.isArray(v)?v.filter(x=>x&&typeof x==='object'&&!Array.isArray(x)) as Row[]:[]
const roleLabel:Record<string,string>={admin:'Administrador',manager:'Gestor',collaborator:'Colaborador'}

export default async function AdminPage(){
  const workspace=await requireCompanyPermission('admin_view'),supabase=await createClient(),rpc=supabase as unknown as RpcClient
  const {data,error}=await rpc.rpc('get_company_admin_command_center',{target_company_id:workspace.company.id})
  if(error)return <AppShell companyName={workspace.company.name} role={workspace.membership.role} permissions={workspace.permissions}><section className="workspace-error"><strong>Não foi possível carregar a Administração.</strong><span>{error.message}</span></section></AppShell>
  const payload=asRecord(data),members=asRows(payload.members),stages=asRows(payload.pipeline_stages),dimensions=asRows(payload.v6_dimensions),portfolios=asRows(payload.portfolios),imports=asRecord(payload.imports),activeMembers=members.filter(m=>m.is_active!==false),formulaReady=dimensions.filter(d=>d.formula_ready===true).length,canManage=workspace.membership.role==='admin'
  return <AppShell companyName={workspace.company.name} role={workspace.membership.role} permissions={workspace.permissions}>
    <PageHeading eyebrow="Admin" title="Administração da incorporadora" context="Acessos, governança, configuração operacional e saúde da estrutura"/>
    <section className={styles.metrics}><article><span>Usuários ativos</span><strong>{activeMembers.length}</strong><small>{members.length-activeMembers.length} inativos</small><UsersRound size={17}/></article><article><span>Carteiras</span><strong>{portfolios.length}</strong><small>estrutura comercial</small><Network size={17}/></article><article><span>Etapas</span><strong>{stages.filter(s=>s.is_active!==false).length}</strong><small>pipeline configurado</small><Settings2 size={17}/></article><article><span>V6</span><strong>{formulaReady}/{dimensions.length}</strong><small>fórmulas calibradas</small><BrainCircuit size={17}/></article><article><span>Importações</span><strong>{integer.format(amount(imports.count))}</strong><small>{integer.format(amount(imports.rows))} linhas processadas</small><Database size={17}/></article></section>
    <section className={styles.governance}><ShieldCheck size={20}/><div><span>HIERARQUIA DE ACESSO</span><b>Admin da incorporadora não cria outro admin</b><p>Novos administradores continuam sob controle da VETRO Platform. Nesta área, o cliente libera Gestores e Colaboradores e define permissões adicionais somente para colaboradores.</p></div></section>
    {canManage?<CompanyInviteMember companyId={workspace.company.id}/>:null}
    <section className={styles.panel}><header><div><span>ACESSOS</span><h2>Usuários da incorporadora</h2></div><small>{members.length} registros</small></header><div className={styles.memberList}>{members.map(member=>{const permissions=asRows(member.permissions);return <article key={text(member.user_id)} className={member.is_active===false?styles.inactive:''}><div className={styles.avatar}>{text(member.name,'U').slice(0,1).toUpperCase()}</div><div><b>{text(member.name,'Usuário')}</b><span>{roleLabel[text(member.role)]??text(member.role)} · {member.is_active===false?'inativo':'ativo'}</span></div><MemberAccessManager active={member.is_active!==false} companyId={workspace.company.id} current={permissions} role={text(member.role)} userId={text(member.user_id)}/></article>})}</div></section>
    <section className={styles.grid}><article className={styles.panel}><header><div><span>PIPELINE</span><h2>Etapas operacionais</h2></div><small>{stages.length}</small></header><div className={styles.stageList}>{stages.map(s=><div key={text(s.id)}><span>{integer.format(amount(s.position))}</span><b>{text(s.name)}</b><small>{text(s.stage_type)}</small></div>)}</div></article><article className={styles.panel}><header><div><span>V6</span><h2>Dimensões e pesos</h2></div><Link href="/intelligence">Abrir Intelligence</Link></header><div className={styles.stageList}>{dimensions.map(d=><div key={text(d.id)}><span>{text(d.key).toUpperCase()}</span><b>{text(d.name)}</b><small>{decimal.format(amount(d.weight)*100)}% · {d.formula_ready?'fórmula pronta':'calibração'}</small></div>)}</div></article></section>
    <section className={styles.grid}><article className={styles.panel}><header><div><span>CARTEIRAS</span><h2>Estrutura comercial</h2></div><small>{portfolios.length}</small></header><div className={styles.stageList}>{portfolios.map(p=><div key={text(p.id)}><span>{p.is_active===false?'off':'on'}</span><b>{text(p.name)}</b><small>{text(p.manager_name,'sem responsável')}</small></div>)}</div></article><article className={styles.panel}><header><div><span>GOVERNANÇA</span><h2>Saúde operacional</h2></div><ShieldCheck size={16}/></header><div className={styles.settingList}><div><span>Última importação</span><b>{imports.latest?dateTime.format(new Date(String(imports.latest))):'—'}</b></div><div><span>Importações concluídas</span><b>{integer.format(amount(imports.completed))}</b></div><div><span>Linhas processadas</span><b>{integer.format(amount(imports.rows))}</b></div><div><span>V6</span><b>{formulaReady===dimensions.length&&dimensions.length>0?'calibrado':'em calibração'}</b></div></div></article></section>
  </AppShell>
}