'use client'

import { FileUp, LoaderCircle } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import styles from './page.module.css'

type RpcClient={rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}>}
const allowed=['csv','xlsx','xls']
export function ImportUpload({companyId}:{companyId:string}){const router=useRouter(),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage('');setError('');try{const form=new FormData(event.currentTarget),file=form.get('file');if(!(file instanceof File)||!file.size)throw new Error('Selecione um arquivo.');const ext=file.name.split('.').pop()?.toLowerCase()??'';if(!allowed.includes(ext))throw new Error('Use CSV, XLSX ou XLS.');if(file.size>25*1024*1024)throw new Error('O arquivo deve ter até 25 MB.');const source=String(form.get('source')??'manual_upload').trim()||'manual_upload';const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${companyId}/${new Date().toISOString().slice(0,10)}-${crypto.randomUUID()}-${safe}`;const supabase=createClient();const upload=await supabase.storage.from('vetro-imports').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(upload.error)throw new Error(upload.error.message);const rpc=supabase as unknown as RpcClient;const registered=await rpc.rpc('register_import_upload',{target_company_id:companyId,upload_source:source,upload_file_name:file.name,storage_path:path,file_size:file.size,mime_type:file.type||null});if(registered.error){await supabase.storage.from('vetro-imports').remove([path]);throw new Error(registered.error.message)}event.currentTarget.reset();setMessage('Arquivo recebido. Ele entrou na fila de validação e processamento.');router.refresh()}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível enviar o arquivo.')}finally{setLoading(false)}}return <form className={styles.uploadForm} onSubmit={submit}><div><FileUp size={19}/><div><b>Enviar nova fonte</b><span>CSV, XLSX ou XLS · até 25 MB · bucket privado</span></div></div><label><span>Origem</span><input name="source" placeholder="Ex.: pipeline mensal, indicadores comerciais"/></label><label><span>Arquivo</span><input name="file" type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required/></label><button disabled={loading} type="submit">{loading?<LoaderCircle className="spin" size={14}/>:<FileUp size={14}/>} {loading?'Enviando…':'Enviar para VETRO'}</button>{message?<p className={styles.success}>{message}</p>:null}{error?<p className={styles.error}>{error}</p>:null}</form>}
